### ISSUE TITLE
Meta: Functional Verification for Kyber

### ISSUE THREAD

**Issue by karthikbhargavan** [cryspen/libcrux#143]
This is a meta-issue tracking formal functional correctness proofs for the Kyber code.
Currently, all module checked below are fully verified with respect to a high-level spec of Kyber in F*.

- [x]  Libcrux.Kem.Kyber.Constants.fst
- [x]  Libcrux.Digest.fsti
- [x]  Libcrux.Kem.Kyber.Hash_functions.fst
- [x]  Libcrux.Kem.Kyber.Kyber768.fst
- [x]  Libcrux.Kem.Kyber.Kyber1024.fst
- [x]  Libcrux.Kem.Kyber.Kyber512.fst
- [x]  Libcrux.Kem.Kyber.fst
- [x]  Libcrux.Kem.Kyber.Types.fst
- [x]  Libcrux.Kem.Kyber.Ind_cpa.fst
- [x]  Libcrux.Kem.Kyber.Arithmetic.fst
- [x]  Libcrux.Kem.Kyber.Compress.fst
- [x]  Libcrux.Kem.Kyber.Constant_time_ops.fst
- [ ] #163
- [ ] #164
- [ ] #165
- [ ] #166

**Comment by karthikbhargavan** [comment]
See PR #161

**Comment by franziskuskiefer** [comment]
The biggest chunk was done in #161. We'll track the remaining issues from above separately.
