### ISSUE TITLE
Libcrux.Kem.Kyber.Serialize.fst

### ISSUE THREAD

**Issue by karthikbhargavan** [cryspen/libcrux#165]
Verify functional correctness of compression and serialization in `Compress`, `Serialize`, and `Ind_cpa`

## Roadmap
- [x] `serialize_uncompress_ring_element` (PR #202)
- [ ] `compress_then_serialize_5_`
    - *in progress*
    - almost TCing, I think the loop body is a bit too big for Z3
    - [ ] split the function in smaller ones
- [ ] other functions
