### ISSUE TITLE
Formally Verify ML-KEM (Portable + AVX2)

### ISSUE THREAD

**Issue by karthikbhargavan** [cryspen/libcrux#454]
Some dependencies:

* ML-KEM Spec: [https://github.com/cryspen/libcrux/issues/144](https://github.com/cryspen/libcrux/issues/144)   
* Intrinsics Spec: [https://github.com/cryspen/libcrux/issues/452](https://github.com/cryspen/libcrux/issues/452)   
* Secret Independence: [https://github.com/cryspen/libcrux/issues/453](https://github.com/cryspen/libcrux/issues/453)   
* ~~Bounded Integers: [https://github.com/hacspec/hax/issues/798](https://github.com/hacspec/hax/issues/798)~~ (we don't use bounded integers)
* Iterators:~~[https://github.com/hacspec/hax/issues/394](https://github.com/hacspec/hax/issues/394),  [https://github.com/hacspec/hax/issues/605](https://github.com/hacspec/hax/issues/605)~~ (we use https://github.com/hacspec/hax/pull/857)
* https://github.com/cryspen/libcrux/issues/566
* https://github.com/cryspen/libcrux/issues/565

ML-KEM Verification tasks:

* vector/portable  
  - [x] vector\_type.rs  
        * status: verified  
  - [ ] arithmetic.rs  
        * status: cleanup 
        * proof dependencies: bounded integers  
        * note: previous proofs in Libcrux.Kem.Kyber.Arithmetic.fst (8/12)  
        * estimate changes: small  
  - [ ] compress.rs  
        * status: cleanup 
        * proof dependencies: bounded integers  
        * note: previous proofs in Libcrux.Kem.Kyber.Compress.fst (3/5)  
        * estimate changes: small  
  - [ ] ntt.rs  
        * status: cleanup  
        * proof dependencies: bounded integers  
        * note: helpful proofs in Libcrux.Kem.Kyber.Ntt.fst (5/11)  
        * estimate changes: medium  
  - [x] sampling.rs  
        * status: panic free 
        * note: previous proofs in Libcrux.Kem.Kyber.Sampling.fst (1/1)  
        * estimate changes: small  
  - [ ] serialize.rs  
        * status: verified  
        * note: helpful proofs in Libcrux.Kem.Kyber.Serialize.fst (?/22)  
        * estimate changes: large  
* vector/avx2  
  - [ ] arithmetic.rs  
        * status: cleanup 
        * proof dependencies: libcrux-intrinsics, portable/arithmetic.rs  
        * note: no previous proofs (0/11)  
        * estimate changes: medium  
  - [ ] compress.rs  
        * status: cleanup  
        * proof dependencies: libcrux-intrinsics, portable/compress.rs  
        * note: no previous proofs (0/4)  
        * estimate changes: small  
  - [ ] ntt.rs  
        * status: cleanup 
        * proof dependencies: libcrux-intrinsics, portable/ntt.rs  
        * note: no previous proofs (0/7)  
        * estimate changes: medium  
  - [ ] sampling.rs  
        * status: panic free  
        * proof dependencies: libcrux-intrinsics, portable/sampling.rs  
        * note: no previous proofs (0/1)  
        * estimate changes: small  
  - [x] serialize.rs  
        * status: partially verified   
        * proof dependencies: libcrux-intrinsics, portable/serialize.rs  
        * note: no previous proofs (0/12)  
        * estimate changes: large  
* generic  
  - [x] types.rs  
        * status: verified  
  - [x] utils.rs  
        * status: verified 
        * note: no previous proofs (0/1)  
        * estimate changes: small  
  - [x] constants.rs  
        * status: verified  
  - [x] hash\_functions.rs  
        * status: verified  
  - [x] constant\_time\_ops.rs  
        * status: verified 
        * note: previous proofs in Libcrux.Kem.Kyber.Constant\_time\_ops.fst (3/7)  
        * estimate changes: small  
  - [x] Ind\_cca.rs  
        * status: verified (memory) 
        * note: previous proofs in Libcrux.Kem.Kyber.fst (5/10)  
        * estimate changes: medium
  - [ ] Ind\_cpa.rs  
        * status: panic-free 
        * proof dependencies: loop invariant  
        * note: previous panic-freedom proofs in Libcrux.Kem.Ind\_cpa.fst (9/13) {7/9 proofs have P-F admits}  
        * estimate changes: medium  
  - [ ] sampling.rs  
        * status: panic-free  
        * proof dependencies: loop invariant  
        * note: previous proofs in Libcrux.Kem.Kyber.Sampling.fst (3/5)  
        * estimate changes: medium  
  - [ ] serialize.rs  
        * status: panic-free  
        * proof dependencies: loop invariant  
        * note: previous proofs in Libcrux.Kem.Kyber.Serialize.fst (16/18)  
        * estimate changes: medium  
  - [ ] matrix.rs  
        * status: panic-free  
        * proof dependencies: loop invariant  
        * note: previous proofs in Libcrux.Kem.Kyber.Matrix.fst (5/5)  
        * estimate changes: small  
  - [ ] polynomial.rs  
        * status: cleanup 
        * note: no previous proofs (0/9)  
        * estimate changes: medium  
  - [ ] ntt.rs  
        * status: cleanup 
        * proof dependencies: loop invariant  
        * note: helpful proofs in Libcrux.Kem.Kyber.Ntt.fst (7/8)  
        * estimate changes: medium  
   - [ ] invert\_ntt.rs  
        * status: cleanup  
        * proof dependencies: loop invariant  
        * note: helpful proofs in Libcrux.Kem.Kyber.Ntt.fst (3/6)  
        * medium  
* top-level APIs
  - [x] ind\_cca/instantiations.rs  
        * status: panic-free  
  - [x] ind\_cca/multiplexing.rs  
        * status: panic-free
  - [x] mlkem512.rs  
        * status: panic-free  
  - [ ] mlkem768.rs  
        * status: panic-free  
  - [x] mlkem1024.rs  
        * status: panic-free

**Comment by karthikbhargavan** [comment]
We have started formally verifying modules, and will be incrementally doing PRs to dev, which is not the proof-oriented branch. The main reason to use dev and not main is that while we incrementally prove individual modules (e.g. IND-CCA), we will need to add assumes and admits into the modules it depends on (e.g. IND-CPA). So to avoid clutter on main, we propose to use dev for now. It is also the case that the `cfg(hax)` style is not yet working perfectly, so this allows us to temporarily add a dependency to hax-lib on `dev` without contaminating main. The goal is to merge main into dev very regularly, say nightly.

**Comment by karthikbhargavan** [comment]
We still have three tasks ongoing:
* Lucas: https://github.com/cryspen/libcrux/issues/535
* Mamone: https://github.com/cryspen/libcrux/issues/565
* Karthik: https://github.com/cryspen/libcrux/issues/566

**Comment by karthikbhargavan** [comment]
We should allocate some resources for secret independence:
* https://github.com/cryspen/libcrux/issues/453

This can either be done just for ML-KEM, or for ML-KEM+ML-DSA, or for libcrux more generally.

**Comment by karthikbhargavan** [comment]
We delivered the proofs. Some todos remain which will be tracked in a new issue.
