### ISSUE TITLE
[ML-DSA] C Extraction

### ISSUE THREAD

**Issue by franziskuskiefer** [cryspen/libcrux#706]
Tracking issue for C extraction of the ML-DSA code.

* #707 
* #710

---

Eurydice issues we work around for now, or block us
- [ ] https://github.com/AeneasVerif/eurydice/issues/102
- [ ] https://github.com/AeneasVerif/eurydice/issues/100
- [ ] https://github.com/AeneasVerif/eurydice/issues/99
- [ ] https://github.com/AeneasVerif/eurydice/issues/104
- [ ] https://github.com/AeneasVerif/eurydice/issues/105
- [ ] https://github.com/AeneasVerif/eurydice/issues/106
- [ ] https://github.com/AeneasVerif/eurydice/issues/107
- [ ] https://github.com/AeneasVerif/eurydice/issues/115

hax issues we work around for now
- [ ] https://github.com/hacspec/hax/issues/1171

**Comment by franziskuskiefer** [comment]
[Eurydice doesn't translate enums correctly](https://github.com/AeneasVerif/eurydice/issues/102) right now. We may have to change the error handling for that

**Comment by franziskuskiefer** [comment]
A first version was merged in #710
